### ISSUE TITLE
Improvements regarding system shutdown and usage of JavaTestKit

### ISSUE THREAD

**Issue by eshepelyuk** [zapodot/akka-test-junit#2]
Hello @zapodot 
What is the Currently state of the project ? Are you still maintaining it ?
I have an idea for some improvement and PR

**Comment by zapodot** [comment]
Hi! All suggestions and PR's are more than welcome ;-)

Sondre

20. sep. 2016 6.39 a.m. skrev "Evgeny Shepelyuk" <notifications@github.com>:

**Comment by eshepelyuk** [comment]
Great !
So, basically, I have two proposals for now

1. Use `JavaTestKit#shutdown` when stopping actor system, instead of `ActorSystem#shutdown`. The first method allows to wait until system completely stopped, thus helping to avoid various race conditions that can happens between rests.

1. For the rule I'd like to introduce a method for obtaining instance of `JavaTestKit`, I.e `new JavaTestKit(system)`. It's a common pattern in our projects to instantiate `ActorSystem` and then corresponding `JavaTestKit`, so that method could reduce code duplication in tests.

What do you think ?

**Comment by zapodot** [comment]
1. Sounds like a good idea!
2. No problem 👍

**Comment by eshepelyuk** [comment]
>> Only thing to consider: The JavaTestKit created needs to be shutdown cleanly. Either should a reference to the given TestKit be kept for reference and cleaned up after the tests has completed OR we have to leave this responsibility to the developer of the test

Well, `JavaTestKit#shutdown` just calls static method `JavaTestKit#shutdownActorSystem()`.
So, implementing point 1 will solve the issue.

**Comment by zapodot** [comment]
Another aproach will be to extend the existing @Rule and create a JavaTestKitRule that takes care of both startup and shutdown. The drawback is that you can have only one JavaTestKit instance per test. Would that cause any problems for you @eshepelyuk?

**Comment by eshepelyuk** [comment]
I don't see any problem, just not clearly understand the benefits of creating a new `@Rule` ? 
Can you provide more details ?

**Comment by zapodot** [comment]
I do think that a JavaTestKitRule will cover a lot of use cases as I suspect that many people need to create a JavaTestKit anyway. Having all the logic contained in a rule ensures that all resources are freed after the test has completed and also avoids code duplication in people's tests.

**Comment by zapodot** [comment]
I have added a new TestKitRule and a test class to show how it may be used. It would be awesome if you would have a look at [TestKitRuleTest](https://github.com/zapodot/akka-test-junit/blob/master/src/test/java/org/zapodot/akka/junit/TestKitRuleTest.java) and see if it indeed serves your use-cases. If you are satisfied I will create a new release ASAP

**Comment by eshepelyuk** [comment]
Hello

The code looks great, doing exactly what we've been missing.
I just still have unanswered question about what are the benefits of having two separate `@Rule`, i.e. 

* `ActorSystemRule`
* `TestKitRule`

Don't you think it's just rather confusing to pick up which one to choose ?

**Comment by zapodot** [comment]
Ok: that's a valid point. They are already almost identical. I'll keep the ActorSystemRule move the JavaTestKit functionality over there. I will look into it at some point in the comming days..

Anyway: thank you for your input

**Comment by eshepelyuk** [comment]
Thanks for your work on this, waiting forward for the release :)

**Comment by zapodot** [comment]
As I just released v. 1.2.0 that contains the changes discussed in this ticket, I am closing it 👍

**Comment by eshepelyuk** [comment]
Unfortunately during shutdown it's not using `verifySystemShutdown`  = true parameter in `akka.testkit.JavaTestKit#shutdownActorSystem(akka.actor.ActorSystem, java.lang.Boolean)`

This is usually a main cause of various bugs. Could you please add it ?

**Comment by zapodot** [comment]
Sure!

Could you open a new github issue for that particular bug. It makes it
easier to seperate it from other issues.

**Comment by eshepelyuk** [comment]
Created Issue #5
