### ISSUE TITLE
[proposal] Change in-memory journal plugin

### ISSUE THREAD

**Issue by eshepelyuk** [zapodot/akka-test-junit#4]
Currently used [plugin](https://github.com/michaelpisula/akka-journal-inmemory) by @michaelpisula seems not maintained anymore.

I suggest to replace it with [another one](https://github.com/dnvriend/akka-persistence-inmemory) by @dnvriend 
- it's quite active
- it has journal and snapshot support
- it has read journal support as well

**Comment by zapodot** [comment]
Should be fairly easy to do. I will look into that shortly

**Comment by eshepelyuk** [comment]
I just started working on this and it seems will be not so easy, because requires AKKA version update as well. If you don't object I can try to finish this and submit a PR.

**Comment by zapodot** [comment]
The problem with moving to Akka 2.4.x is that it seems to requires Java 8. As a lot of people, especieally working in corporations are still stuck at Java 7, I would like to postphone that transition for a while.

**Comment by eshepelyuk** [comment]
Yeah, that makes sense.

**Comment by zapodot** [comment]
Implementing this in the future will solve issue #1 completely
