### ISSUE TITLE
Support Akka 2.5.0

### ISSUE THREAD

**Issue by zapodot** [zapodot/akka-test-junit#6]
The upcoming release of Akka 2.5 requires some changes as for instance the JavaTestKit has been deprecated

**Comment by drissamri** [comment]
@zapodot will there be any new release of this artifact?

**Comment by zapodot** [comment]
@drissamri sure. Just haven't been much in the Akka-world lately. But if you need it I will have a fresh look at it as soon as possible

**Comment by drissamri** [comment]
I upgraded the Akka version of our production app today and looking if we should drop this or not. But if you can provide an updated version I'd gladly use it. 👍

**Comment by drissamri** [comment]
On second thought, let me give a quick try to send you a pull request. Not much Akka experience, but this seems straight forward

**Comment by zapodot** [comment]
If you do, please check the akka-2.5 branch.



21. mar. 2018 13:35 skrev "Driss Amri" <notifications@github.com>:

**Comment by drissamri** [comment]
Done: https://github.com/zapodot/akka-test-junit/pull/7

**Comment by drissamri** [comment]
Any help to get this one merged and released would be greatly appreciated so I continue on my project. Thank you for your library and support.

**Comment by zapodot** [comment]
Just released this as part of the 2.0.0 release. Thanks to @drissamri for the effort, but seems like I had already done the job in the akka-2.5 branch
